version: '3.7'
services:
  web:
    tty: true
    image: nginx:1.10.3-alpine
    container_name: mars_web
    volumes:
      - ./docker/nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www
      - ./docker/data/nginx/logs:/var/log/nginx/
    ports:
      - 8080:80
    depends_on:
      - app
    links:
      - app

  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    user: "1000:1000"
    container_name: mars_app
    volumes:
      - ./:/var/www
    links:
      - db

  db:
    image: mariadb:10.3
    container_name: mars_db
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mars
      MYSQL_USER: mars
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mars_pma
    links:
      - db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: changeme
